### ISSUE TITLE
Change prompt to [cmd]>> 

### ISSUE THREAD

**Issue by Zearin** [defunkt/repl#11]
`repl` is awesome.  In fact sometimes I'm using it for a couple of different programs.  

The thing is, if I open too many at once, or I leave for food and come back to pick up where I left off, I quickly forget and have absolutely no idea which command I’ve repl-ed in which terminal.  

It'd be fantastic if repl put the command it’s currently wrapping into the prompt.  ☺

**Comment by defunkt** [comment]
It does =)

d872add41d80a01cc8ba31e9cc8a04e690b1b739

```
$ repl redis-cli
redis-cli>> info
redis_version:2.0.4
```

**Comment by Zearin** [comment]
Oh…defunkt, you are just too good. ☺ 

Thanks!
