### ISSUE TITLE
exit/quit commands

### ISSUE THREAD

**Issue by bry4n** [defunkt/repl#4]
Since all commands' arguments are not included with 'exit' and 'quit'. I think its safe to use exit/quit command to exit repl session.

my branch: http://github.com/bry4n/repl/tree/exit

**Comment by stephencelis** [comment]
I can't think of any CLIs that take either argument, but I'm not sure it's completely safe to override exit/quit. What if it were to be handled more like the Python interactive shell, warning you upon "exit" or "quit":

```
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
```

Really, it could just warn you to use Ctrl-D, which is faster than typing "exit()" or "quit()" anyway.

**Comment by bry4n** [comment]
Great idea. Done @ http://github.com/bry4n/repl/commit/6ed4d0385162e095abdd2fe26c29cd24c913c54d

**Comment by defunkt** [comment]
Added in 20cbb4ec35840e1cecc4f36ea846b616300d492a - thanks!
