### ISSUE TITLE
Pipe line input to command's stdin

### ISSUE THREAD

**Issue by jdp** [defunkt/repl#7]
Some programs I'd like a REPL for don't take input from the command line, but from standard input. My branch lets you provide the --stdin switch to pipe the line input to the command's standard input. I also fixed the which rlwrap call, it now also pipes standard error to /dev/null. On my machine I was still seeing the which error output when not having rlwrap installed.

EDIT: you can also use `repl ./command`, before the ./ notation was causing rlwrap to die.

My branch is here: http://github.com/jdp/repl/tree/jdp-stdin

**Comment by defunkt** [comment]
What's an application that takes input on stdin?

**Comment by jdp** [comment]
The simplest (but most useless) example I can think of is `cat`. Any program that responds to having input piped to it can then work this way, which makes `repl` an ideal testbed for working with those programs (when writing shell scripts, for example). My own personal use is mostly toy languages/interpreters, where I don't feel like writing a REPL or writing routines to parse C strings, I just use `fgetc(stdin)` to get character input from stdin.

**Comment by defunkt** [comment]
Merged into 0.2.1, thanks!
